name: smart_agri_app
description: "AgriScan - Plant Intelligence Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter_localizations:
    sdk: flutter

  geolocator: ^12.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio:
  shared_preferences:
  image_picker:
  table_calendar:
  flutter_bloc:
  fl_chart: ^0.64.0
  equatable:
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^5.2.3
  screenshot: ^3.0.0
  gallery_saver_plus: ^3.0.1
  google_mlkit_barcode_scanning: ^0.12.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  awesome_notifications: ^0.11.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/agriscan_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/agriscan_logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false